---
title: "ReadMe"
output: html_document
---

# Human Activity Recognition Using Smartphones Dataset

The "RunData" dataset is a cleaned version of the datasets described below (reference: README.txt from the files downloaded for this project):

"The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

"The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain."

## For each record, the provided data are:

- 180 records
- A unique identifier for each subject
- An activity label (see Code Book for levels)
- mean values calculated for all mean() and std() values made available in the raw data (79 variables)

## The following files are included here:

- 'README.Rmd'
- 'CodeBook_RunData.pdf' - descriptors for the variables in the dataset
- 'run_analysis.R' - code for deriving the given clean dataset. See comments in the code for a step-by-step explanation of the cleaning process.

### PLEASE NOTE: 

All features variables are NORMALIZED - bounded in [-1, 1].
